In [2]:
import numpy as np


In [3]:
distance=[12,44,54,70,50]

In [4]:
time=[0.27,0.54,0.77,0.55,0.29]

In [5]:
speed=distance/time


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [7]:

a=np.arange(10,90,10)

In [9]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [11]:
a.shape()

TypeError: 'tuple' object is not callable

In [13]:
a.shape

(8,)

In [15]:
a=np.arange(10,90,10).reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [17]:
b=np.arange(10,90,10).reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [19]:
b=np.arange(10,90,10).reshape(3,3)
b

ValueError: cannot reshape array of size 8 into shape (3,3)

In [21]:
b=np.arange(10,100,10).reshape(3,3)
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
b[0:3:2]

array([[10, 20, 30],
       [70, 80, 90]])

In [25]:
b[1:3:]

array([[40, 50, 60],
       [70, 80, 90]])

In [27]:
b[:-1]

array([[10, 20, 30],
       [40, 50, 60]])

In [29]:
b[2:-2]

array([], shape=(0, 3), dtype=int32)

In [31]:
b[2:1]

array([], shape=(0, 3), dtype=int32)

In [33]:
b[1:-1]

array([[40, 50, 60]])

In [35]:
type(b)

numpy.ndarray

In [36]:
distance=[200,400,300,600]

In [37]:
time=[2.5,3.5,4.5,5.5]

In [38]:
dist1=np.array(distance)

In [39]:
timen=np.array(time)


In [41]:
speed=distance/timen

NameError: name 'timen' is not defined

In [43]:
timet=np.array(time)

In [45]:
speed=distance/timet
speed

array([ 80.        , 114.28571429,  66.66666667, 109.09090909])

In [47]:
total=distance+timet
total

array([202.5, 403.5, 304.5, 605.5])

In [49]:

newdistance=distance**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [51]:
newdistance=distance*2
newdistance

[200, 400, 300, 600, 200, 400, 300, 600]

In [54]:
timex=[2.5,3.5,7.5]


In [55]:
speed=distance/timex
speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [57]:
print(np.random.randn(2,2))

[[-2.27475056 -1.6306267 ]
 [-0.04798762  0.46692124]]


In [59]:
print(np.random.randn(2,4))

[[ 1.73082077  1.14018873  0.00958813  0.20293807]
 [-1.43592319  0.06864627  0.10963195 -0.63279324]]


In [61]:
print(np.random.randint(34))


7


In [63]:
print(np.random.randint(18,90,500))

[24 87 24 57 20 22 75 23 80 25 57 28 35 42 39 53 89 33 23 32 30 64 31 75
 48 68 64 81 75 31 27 67 38 51 89 47 78 75 85 42 30 57 34 47 89 72 60 42
 33 78 35 50 80 36 25 32 62 34 18 42 89 26 67 82 73 37 23 81 46 40 54 25
 37 59 25 76 51 19 53 25 25 23 27 20 48 24 46 29 88 49 30 53 26 45 89 83
 32 30 84 79 34 73 37 22 35 75 44 65 70 37 32 43 68 46 75 31 50 45 26 57
 45 60 60 28 32 50 20 53 84 85 58 33 31 31 20 22 45 25 72 45 54 53 70 34
 71 43 84 80 51 33 54 32 21 67 50 36 57 59 80 30 83 49 70 23 24 53 24 62
 75 41 54 47 19 47 80 89 56 23 20 78 89 46 36 34 29 29 85 84 57 75 20 54
 41 19 78 32 89 59 89 36 37 57 64 84 31 20 78 34 76 19 23 31 28 58 83 89
 85 55 81 30 25 79 64 18 60 36 81 68 63 30 56 42 61 88 33 53 86 36 26 31
 84 45 47 42 58 75 65 51 29 51 77 23 54 29 27 49 42 26 86 24 74 42 38 56
 18 77 67 40 22 25 71 53 80 27 82 38 33 65 29 78 32 82 34 66 23 54 65 70
 72 71 82 31 42 50 31 22 70 55 33 39 25 45 69 73 21 32 59 55 51 36 87 26
 62 88 35 87 54 89 86 45 68 25 73 71 84 66 40 67 23

In [65]:
print(np.random.randint(18,90,2))

[58 73]


In [67]:
ages=np.random.randint(18,90,500)
np.mean(ages)

52.942

In [71]:
from scipy import stats

In [73]:
stats.mode(ages)

ModeResult(mode=array([18]), count=array([13]))

In [74]:
from scipy import stats


In [76]:
np.median(ages)

52.0

In [77]:
agesn=[7,8,9,3,4,10]
np.median(agesn)

7.5